name: build-sqlite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ubuntu-latest
        ruby: 2.7
    runs-on: ${{ matrix.os }}
    env:
      AWS_S3_WRITE_ACCESS_KEY: ${{ secrets.AWS_S3_WRITE_ACCESS_KEY }}
      AWS_S3_WRITE_SECRET_KEY: ${{ secrets.AWS_S3_WRITE_SECRET_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: |
        rake spine
